/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthDocsRouteImport } from './routes/_auth/docs'
import { Route as AuthFlagsRouteImport } from './routes/_auth/flags'
import { Route as AuthRealtimeRouteImport } from './routes/_auth/realtime'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthWorkersRouteImport } from './routes/_auth/workers'
import { Route as AuthCollectionsIndexRouteImport } from './routes/_auth/collections/index'
import { Route as AuthCollectionsMoulNameRouteImport } from './routes/_auth/collections/$moulName'
import { Route as AuthRecordsMoulNameRouteImport } from './routes/_auth/records/$moulName'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFlagsRoute = AuthFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRealtimeRoute = AuthRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkersRoute = AuthWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsIndexRoute = AuthCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsMoulNameRoute = AuthCollectionsMoulNameRouteImport.update({
  id: '/collections/$moulName',
  path: '/collections/$moulName',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecordsMoulNameRoute = AuthRecordsMoulNameRouteImport.update({
  id: '/records/$moulName',
  path: '/records/$moulName',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/docs': typeof AuthDocsRoute
  '/flags': typeof AuthFlagsRoute
  '/realtime': typeof AuthRealtimeRoute
  '/settings': typeof AuthSettingsRoute
  '/workers': typeof AuthWorkersRoute
  '/collections/$moulName': typeof AuthCollectionsMoulNameRoute
  '/records/$moulName': typeof AuthRecordsMoulNameRoute
  '/collections/': typeof AuthCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/docs': typeof AuthDocsRoute
  '/flags': typeof AuthFlagsRoute
  '/realtime': typeof AuthRealtimeRoute
  '/settings': typeof AuthSettingsRoute
  '/workers': typeof AuthWorkersRoute
  '/': typeof AuthIndexRoute
  '/collections/$moulName': typeof AuthCollectionsMoulNameRoute
  '/records/$moulName': typeof AuthRecordsMoulNameRoute
  '/collections': typeof AuthCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/docs': typeof AuthDocsRoute
  '/_auth/flags': typeof AuthFlagsRoute
  '/_auth/realtime': typeof AuthRealtimeRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/workers': typeof AuthWorkersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/collections/$moulName': typeof AuthCollectionsMoulNameRoute
  '/_auth/records/$moulName': typeof AuthRecordsMoulNameRoute
  '/_auth/collections/': typeof AuthCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/analytics'
    | '/docs'
    | '/flags'
    | '/realtime'
    | '/settings'
    | '/workers'
    | '/collections/$moulName'
    | '/records/$moulName'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/analytics'
    | '/docs'
    | '/flags'
    | '/realtime'
    | '/settings'
    | '/workers'
    | '/'
    | '/collections/$moulName'
    | '/records/$moulName'
    | '/collections'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/setup'
    | '/_auth/analytics'
    | '/_auth/docs'
    | '/_auth/flags'
    | '/_auth/realtime'
    | '/_auth/settings'
    | '/_auth/workers'
    | '/_auth/'
    | '/_auth/collections/$moulName'
    | '/_auth/records/$moulName'
    | '/_auth/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs': {
      id: '/_auth/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/flags': {
      id: '/_auth/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AuthFlagsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/realtime': {
      id: '/_auth/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof AuthRealtimeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workers': {
      id: '/_auth/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthWorkersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/': {
      id: '/_auth/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthCollectionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/$moulName': {
      id: '/_auth/collections/$moulName'
      path: '/collections/$moulName'
      fullPath: '/collections/$moulName'
      preLoaderRoute: typeof AuthCollectionsMoulNameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/records/$moulName': {
      id: '/_auth/records/$moulName'
      path: '/records/$moulName'
      fullPath: '/records/$moulName'
      preLoaderRoute: typeof AuthRecordsMoulNameRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthDocsRoute: typeof AuthDocsRoute
  AuthFlagsRoute: typeof AuthFlagsRoute
  AuthRealtimeRoute: typeof AuthRealtimeRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWorkersRoute: typeof AuthWorkersRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCollectionsMoulNameRoute: typeof AuthCollectionsMoulNameRoute
  AuthRecordsMoulNameRoute: typeof AuthRecordsMoulNameRoute
  AuthCollectionsIndexRoute: typeof AuthCollectionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthDocsRoute: AuthDocsRoute,
  AuthFlagsRoute: AuthFlagsRoute,
  AuthRealtimeRoute: AuthRealtimeRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWorkersRoute: AuthWorkersRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCollectionsMoulNameRoute: AuthCollectionsMoulNameRoute,
  AuthRecordsMoulNameRoute: AuthRecordsMoulNameRoute,
  AuthCollectionsIndexRoute: AuthCollectionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
